[package]
name = "sg2000-pac"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = { version = "1.0", optional = true }
riscv = "0.11.1"
riscv-rt = { version = "0.12.2", optional = true }
vcell = "0.1.3"

[features]
rt = ["riscv-rt"]

