[target.riscv64gc-unknown-none-elf]
rustflags = [
  "-C",
  "link-arg=-Tmemory.x",
  "-C",
  "link-arg=-Tdevice.x",
  "-C",
  "link-arg=-Tlink.x",
  # to include the  .resource_table section
  "-C",
  "link-dead-code",
]

linker = "riscv64-unknown-elf-ld"
runner = "./run_on_target.sh"

[build]
target = "riscv64gc-unknown-none-elf"
